version: '3.8'

services:
  db:
    image: postgres:15
    container_name: gestion-reservation-db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # CORRECTION ICI 👇
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gestion-reservation-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      # CORRECTION ICI 👇
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: gestion-reservation-frontend
    restart: always
    depends_on:
      - backend
    ports:
      # CORRECTION ICI 👇
      - "4200:80"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      # CORRECTION ICI 👇
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: