apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-frontend
  namespace: reservation
spec:
  template:
    spec:
      containers:
        - name: frontend
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: frontend-nginx
            items:
              - key: default.conf
                path: default.conf
